### ISSUE TITLE
SSL error on trains.datascopeanalytics.com

### ISSUE THREAD

**Issue by jeancochrane** [datascopeanalytics/outside-a-train-rumbles-by#2]
I was browsing the Datascope site and bumped into an SSL error from the subdomain that renders the train widget.

Here's what it looks like on datascopeanalytics.com:

<img width="1278" alt="screen shot 2017-05-11 at 1 59 30 pm" src="https://cloud.githubusercontent.com/assets/14170650/25966928/17ca4792-3652-11e7-8f5e-8fa226be39e1.png">

And here's the full error as reported by Firefox:

<img width="1280" alt="screen shot 2017-05-11 at 1 58 10 pm" src="https://cloud.githubusercontent.com/assets/14170650/25966902/08c7aa50-3652-11e7-85c4-74862e725e81.png">

My apologies if this isn't the right place for the issue! I figured I'd be safe and file a report.

**Comment by stringertheory** [comment]
This is indeed the right place, thanks so much for filing the issue!

**Comment by stringertheory** [comment]
Finally fixed this — thanks again @jeancochrane!
